liip_imagine:

    #    # valid drivers options include "gd" or "gmagick" or "imagick"
    #    driver: "gd"
    #

    filter_sets:
        #
        #        # an example thumbnail transformation definition
        #        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
        squared_logo_nano:
            filters:
                scale:
                    dim: [ 80, 24 ]

        squared_thumbnail_nano:
            filters:
                scale:
                    dim: [ 60, 60 ]

        squared_thumbnail_mini:
            filters:
                scale:
                    dim: [ 140, 140]

        squared_thumbnail_small:
            filters:
                scale:
                    dim: [ 250, 250 ]

        actress_thumbnail_md:
            filters:
                scale:
                    dim: [ 380, 380 ]

        squared_thumbnail_md:
            filters:
                scale:
                    dim: [ 500, 500 ]

        squared_thumbnail_min_ob:
            filters:
                thumbnail:
                    size:          [220, 220]
                    mode:          outbound
                    allow_upscale: true

        squared_thumbnail_md_ob:
            filters:
                thumbnail:
                    size:          [500, 500]
                    mode:          outbound
                    allow_upscale: true
        squared_thumbnail_lg:
            filters:
                scale:
                    dim: [ 900, 900 ]
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'