# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads'
    filesystems:
        upload_filesystem:
            adapter: upload_adapter
            alias: League\Flysystem\Filesystem
