twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'